### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by dj2** [cds-snc/.github#14]
I'm not sure why this is called `.github` instead of something like `cds_repository_template` which is a bit more descriptive. Would anyone object to renaming the repository?

**Comment by maxneuvians** [comment]
I think it is convention https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by dj2** [comment]
Ugh, but what happens if I clone the repo? Does it copy in the CONTRIBUTING file? This also explains why I couldn't figure out how the pull_request_template was getting picked up by other repositories.

We seem to be using this in a different way than as a defaulting folder. We clone it and use it as the basis for new repositories.

**Comment by patheard** [comment]
Alright, after chatting with @maxneuvians and @CalvinRodo I have a better idea of the problem.  We're making this project do double duty:

1. Provide magic [community health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types) to any project without them; and
2. Act as a new project template.

I like how this could mean community health files are only maintained in one spot, but also dislike how they're not that discoverable.  Like you said, they don't clone down and I've only seen them in the [project insights tab](https://github.com/cds-snc/cds-website-cms/community) and in a popup for your first issue/PR on the repo.

I think it would make a lot of sense to have separate repos to act as templates for different project types.   As for continuing to use the community health file defaults, I don't have a strong opinion either way - pros/cons to both approaches and all that jazz.  The considerations I can think of are:

* Without this project, we need to backfill them to all our repos; and
* How do we keep them sync'd with changes if we backfill them.

**Comment by dj2** [comment]
Backfilling will be a pain, but doable. Keeping in sync, is that something we need/want? I don't think we really change these files, and if we do, should they be retroactive?

**Comment by patheard** [comment]
I checked out their commits and the only one that really changed was [SECURITY.md](https://github.com/cds-snc/.github/commits/main/SECURITY.md).  In this case it was a change that should be retroactive (new contact email) but we're probably safe to create these as standalone if people want to get rid of the defaults in this project.

**Comment by dj2** [comment]
@maxneuvians @fitore-cds @dorianjp @timarney @CalvinRodo 

Thoughts on keeping this repo as a magical GitHub repo and having it default in files on the GitHub community page?

Personally I found it very confusing, I spent a good half an hour trying to figure out where the pull request template was coming from on one project before giving up. (Prior to knowing this repo did this defaulting)

**Comment by CalvinRodo** [comment]
Personally I'm all for having some defaults imposed on our projects from this repo and creating a few template repos that can be used to setup some default workflows for items such as various project types like Infra as Code etc.. 

It can be a little confusing for sure but then it should probably be documented that we are using this and so it should be documented and added to the dev community onboarding material.

**Comment by patheard** [comment]
I've created a new generic project template:
https://github.com/cds-snc/project-template

My thinking was we could follow this pattern if we create more templates:
* project-template-terraform
* project-template-python
* project-template-typescript

**Comment by dj2** [comment]
Closing this as the name is set and we've got other starter repos.
